"""empty message

Revision ID: 763953af96d9
Revises: 1efa51fd27ac
Create Date: 2024-08-30 13:52:08.662858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763953af96d9'
down_revision: Union[str, None] = '1efa51fd27ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('image', sa.String(), nullable=False))
    op.add_column('episodes', sa.Column('description', sa.String(), nullable=False))
    op.add_column('episodes', sa.Column('rating', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'rating')
    op.drop_column('episodes', 'description')
    op.drop_column('episodes', 'image')
    # ### end Alembic commands ###
